# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dimafilipenko/CLionProjects/lb3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dimafilipenko/CLionProjects/lb3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dimafilipenko/CLionProjects/lb3/CMakeFiles /Users/dimafilipenko/CLionProjects/lb3/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dimafilipenko/CLionProjects/lb3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lb3

# Build rule for target.
lb3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lb3
.PHONY : lb3

# fast build rule for target.
lb3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/build
.PHONY : lb3/fast

Manager.o: Manager.cpp.o

.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i

.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s

.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

ball.o: ball.cpp.o

.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i

.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s

.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/ball.cpp.s
.PHONY : ball.cpp.s

figure.o: figure.cpp.o

.PHONY : figure.o

# target to build an object file
figure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/figure.cpp.o
.PHONY : figure.cpp.o

figure.i: figure.cpp.i

.PHONY : figure.i

# target to preprocess a source file
figure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/figure.cpp.i
.PHONY : figure.cpp.i

figure.s: figure.cpp.s

.PHONY : figure.s

# target to generate assembly for a file
figure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/figure.cpp.s
.PHONY : figure.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/main.cpp.s
.PHONY : main.cpp.s

program.o: program.cpp.o

.PHONY : program.o

# target to build an object file
program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/program.cpp.o
.PHONY : program.cpp.o

program.i: program.cpp.i

.PHONY : program.i

# target to preprocess a source file
program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/program.cpp.i
.PHONY : program.cpp.i

program.s: program.cpp.s

.PHONY : program.s

# target to generate assembly for a file
program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/program.cpp.s
.PHONY : program.cpp.s

square.o: square.cpp.o

.PHONY : square.o

# target to build an object file
square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/square.cpp.o
.PHONY : square.cpp.o

square.i: square.cpp.i

.PHONY : square.i

# target to preprocess a source file
square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/square.cpp.i
.PHONY : square.cpp.i

square.s: square.cpp.s

.PHONY : square.s

# target to generate assembly for a file
square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/square.cpp.s
.PHONY : square.cpp.s

triangle.o: triangle.cpp.o

.PHONY : triangle.o

# target to build an object file
triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/triangle.cpp.o
.PHONY : triangle.cpp.o

triangle.i: triangle.cpp.i

.PHONY : triangle.i

# target to preprocess a source file
triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/triangle.cpp.i
.PHONY : triangle.cpp.i

triangle.s: triangle.cpp.s

.PHONY : triangle.s

# target to generate assembly for a file
triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb3.dir/build.make CMakeFiles/lb3.dir/triangle.cpp.s
.PHONY : triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lb3"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... figure.o"
	@echo "... figure.i"
	@echo "... figure.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
	@echo "... square.o"
	@echo "... square.i"
	@echo "... square.s"
	@echo "... triangle.o"
	@echo "... triangle.i"
	@echo "... triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

